# Generated by Django 4.2 on 2023-05-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ciudad',
            field=models.CharField(default='Desconocido', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='Desconocido', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombreC',
            field=models.CharField(default='Desconocido', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.IntegerField(default=9999999999),
        ),
    ]
