# Generated by Django 4.2 on 2023-05-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_ciudad_profile_direccion_profile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boveda',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Bóvedas disponibles',
            },
        ),
    ]
