# Generated by Django 4.2 on 2023-05-08 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alquiler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquiler',
            options={'verbose_name_plural': 'Alquileres'},
        ),
        migrations.CreateModel(
            name='Difunto',
            fields=[
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_defuncion', models.DateField()),
                ('fecha_ingreso_boveda', models.DateField()),
                ('boveda_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alquiler')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
